# Copyright (c) 2026 Joseph Hale
# SPDX-License-Identifier: MPL-2.0

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
