[tools]
# Python Tools
hatch = "latest"
uv = "latest"
python = [ "3.10", "3.11", "3.12", "3.13", "3.14", "3.15.0rc1" ]

# Base Tools
"aqua:hashicorp/copywrite" = "latest"
actionlint = "latest"
bats = "1.14.0"
markdownlint-cli2 = "latest"
shellcheck = "latest"
shfmt = "latest"
yamlfmt = "latest"
zizmor = "latest"
