name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: CI
      run: |
        git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .
        pwd
        ls -la
        bin/setup.sh
        bin/ci.sh